
import java.util.ArrayList;
import java.util.List;
import java.util.PriorityQueue;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class KnapsackGUI extends javax.swing.JFrame {
    private int n,capacity,counter;
    private Knapsack k;
    /**
     * Creates new form KnapsackGUI1
     */
    public KnapsackGUI() {
        initComponents();
        this.itemButton.setVisible(false);
        this.itemTabel.setVisible(false);
        this.kLabel.setVisible(false);
        this.kText.setVisible(false);
        this.esResultText.setVisible(false);
        this.bnbResultText.setVisible(false);
        this.weight.setVisible(false);
        this.weightLabel.setVisible(false);
        this.value.setVisible(false);
        this.valueLabel.setVisible(false);
        this.startButton.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        weightLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        weight = new javax.swing.JTextField();
        value = new javax.swing.JTextField();
        itemButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        itemTabel = new javax.swing.JTable();
        kLabel = new javax.swing.JLabel();
        kText = new javax.swing.JTextField();
        startButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        esResultText = new javax.swing.JList();
        nLabel4 = new javax.swing.JLabel();
        nText = new javax.swing.JTextField();
        cLabel5 = new javax.swing.JLabel();
        cText = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        restartButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        bnbResultText = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        weightLabel.setText("Weight");

        valueLabel.setText("Value");

        weight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightActionPerformed(evt);
            }
        });

        value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valueActionPerformed(evt);
            }
        });

        itemButton.setText("Add");
        itemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemButtonActionPerformed(evt);
            }
        });

        itemTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Weight", "Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(itemTabel);
        if (itemTabel.getColumnModel().getColumnCount() > 0) {
            itemTabel.getColumnModel().getColumn(0).setResizable(false);
            itemTabel.getColumnModel().getColumn(1).setResizable(false);
            itemTabel.getColumnModel().getColumn(2).setResizable(false);
        }

        kLabel.setText("K Value");

        kText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kTextActionPerformed(evt);
            }
        });

        startButton.setText("Find");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(esResultText);

        nLabel4.setText("Jumlah Item :");

        cLabel5.setText("Kapasitas     :");

        cText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTextActionPerformed(evt);
            }
        });

        jButton3.setText("Start");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        restartButton.setText("Clear");
        restartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartButtonActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(bnbResultText);

        jLabel1.setText("Exhaustive Search");

        jLabel2.setText("Branch and Bound");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(weightLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(weight, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(valueLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(value, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(itemButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(kLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(kText, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(startButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jButton3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(31, 31, 31)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(restartButton)
                .addGap(128, 128, 128))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nLabel4)
                            .addComponent(nText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cLabel5)
                            .addComponent(cText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton3)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(weightLabel)
                        .addComponent(weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(itemButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valueLabel)
                    .addComponent(value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kLabel)
                    .addComponent(kText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(restartButton)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void weightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightActionPerformed

    private void itemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemButtonActionPerformed
        if(counter < n)
        {
            DefaultTableModel model = (DefaultTableModel) itemTabel.getModel();
            model.addRow(new Object[]{"Item"+(counter),Integer.parseInt(weight.getText()),Integer.parseInt(value.getText())});
            counter++;
        }
        this.weight.setText("");
        this.value.setText("");
    }//GEN-LAST:event_itemButtonActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        if(itemTabel.getRowCount() < this.n)
        {
            String message = "Jumlah item kurang dari "+this.n;
            JOptionPane.showMessageDialog(new JFrame(), message, "Dialog",
            JOptionPane.ERROR_MESSAGE);
        }
        else
        {
        Item[] item = new Item[itemTabel.getRowCount()];
        DefaultListModel<String> model = new DefaultListModel<>();
        DefaultListModel<String> model1 = new DefaultListModel<>();
        DefaultTableModel modelTable = (DefaultTableModel) itemTabel.getModel();
        for(int i = 0;i < item.length;i++)
        {
            item[i] = new Item((int)itemTabel.getModel().getValueAt(i,1),(int)itemTabel.getModel().getValueAt(i,2));
        }
        for (int i = itemTabel.getRowCount() - 1; i >= 0; i--)
        {
            modelTable.removeRow(i);
        }
        this.k = new Knapsack(capacity,item);
        Item[] tempItem = k.getItem2();
        counter = 0;
        for(int i = 0;i < tempItem.length;i++)
        {
            modelTable.addRow(new Object[]{"Item"+(counter),tempItem[i].getWeight(),tempItem[i].getValue()});
            counter++;
        }
        long startTime = System.nanoTime();
        k.findBnB2(Integer.parseInt(kText.getText()));
        long endTime   = System.nanoTime();
        long BNBtime = (endTime-startTime);
        startTime = System.nanoTime();
        k.searchES(Integer.parseInt(kText.getText()));
        endTime   = System.nanoTime();
        long EStime = (endTime-startTime);
        PriorityQueue<Node> result = k.getResultBnB();
        PriorityQueue<Data> result1 = k.getResultES();
        while(!result.isEmpty())
        {
            Node temp = result.poll();
            model.addElement(temp.kombinasi+" "+temp.weightSum+" "+temp.lowerBound);
        }
        model.addElement("Time : "+BNBtime);
        while(!result1.isEmpty())
        {
            Data temp = result1.poll();
            model1.addElement(temp.indexBarang+" "+temp.weight+" "+temp.value);
        }
        model1.addElement("Time : "+EStime);
        bnbResultText.setModel(model);
        esResultText.setModel(model1);
        }
    }//GEN-LAST:event_startButtonActionPerformed

    private void cTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cTextActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.n = Integer.parseInt(nText.getText());
        this.counter = 0;
        this.capacity = Integer.parseInt(cText.getText());
        this.itemButton.setVisible(true);
        this.itemTabel.setVisible(true);
        this.kLabel.setVisible(true);
        this.kText.setVisible(true);
        this.esResultText.setVisible(true);
        this.bnbResultText.setVisible(true);
        this.weight.setVisible(true);
        this.weightLabel.setVisible(true);
        this.value.setVisible(true);
        this.valueLabel.setVisible(true);
        this.startButton.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void restartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartButtonActionPerformed
        this.cText.setText("");
        this.nText.setText("");
        this.weight.setText("");
        this.value.setText("");
        this.kText.setText("");
        DefaultListModel<String> model = new DefaultListModel<>();
        DefaultTableModel model1 = (DefaultTableModel) itemTabel.getModel();
        for (int i = itemTabel.getRowCount() - 1; i >= 0; i--)
        {
            model1.removeRow(i);
        }
        this.esResultText.setModel(model);
        this.itemButton.setVisible(false);
        this.itemTabel.setVisible(false);
        this.kLabel.setVisible(false);
        this.kText.setVisible(false);
        this.esResultText.setVisible(false);
        this.bnbResultText.setVisible(false);
        this.weight.setVisible(false);
        this.weightLabel.setVisible(false);
        this.value.setVisible(false);
        this.valueLabel.setVisible(false);
        this.startButton.setVisible(false);
        this.n = 0;
        this.capacity = 0;
        this.k = null;
    }//GEN-LAST:event_restartButtonActionPerformed

    private void kTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kTextActionPerformed

    private void valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valueActionPerformed
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KnapsackGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KnapsackGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KnapsackGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KnapsackGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KnapsackGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList bnbResultText;
    private javax.swing.JLabel cLabel5;
    private javax.swing.JTextField cText;
    private javax.swing.JList esResultText;
    private javax.swing.JButton itemButton;
    private javax.swing.JTable itemTabel;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel kLabel;
    private javax.swing.JTextField kText;
    private javax.swing.JLabel nLabel4;
    private javax.swing.JTextField nText;
    private javax.swing.JButton restartButton;
    private javax.swing.JButton startButton;
    private javax.swing.JTextField value;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JTextField weight;
    private javax.swing.JLabel weightLabel;
    // End of variables declaration//GEN-END:variables
}
